### PR TITLE
feat: update synth to generate v1, v1beta2, v1alpha2 endpoints

### PR DESCRIPTION
**Pull request by steffnay**
This PR contains both the changes to the synth config, as well as the generated output from running synth.

### CODE REVIEW

**Comment by alexander-fenster** [comment]
@steffnay Unfortunately, `synthtool` cannot properly merge client versions for you. I see that you already created `src/index.ts` properly, now you'll need to exclude `src/index.ts` from all copy operations.

Please take a look at the example here: https://github.com/googleapis/nodejs-text-to-speech/blob/master/synth.py#L42

In line 42, `src/index.ts` is excluded from the generation (because otherwise it will be overwritten by the subsequent `synthtool` runs).

**Comment by steffnay** [comment]
@alexander-fenster got it, thanks! Do you know what's up with this 0% code coverage?

**Comment by alexander-fenster** [comment]
@steffnay I'm pretty sure it's something weird going on with codecov.io.  If you look at CI output, it obviously has non-zero coverage:

image

Maybe someone from Yoshi can take a look at the coverage reporting here? @bcoe ?

**Comment by bcoe** [comment]
@steffnay I believe we fixed up coverage the other week, so should stop being weird for you.

**Pull request closed without merging**
